---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update_repositorys
      pacman:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/copydotfiles.yml
    - include: tasks/add_sudo.yml
