- name: decrypt and unpack files
  unarchive:
    decrypt: yes
    dest: /home/nsksbjii/
    owner: nsksbjii
    src: files.tar

- name: copy vimrc
  copy:
    src: /home/nsksbjii/files/vimrc
    dest: /home/nsksbjii/.vimrc

- name: create .config folder
  file:
    dest: /home/nsksbjii/.config
    state: directory

- name: copy dotconfigfolder
  synchronize:
    src: /home/nsksbjii/files/config
    dest: /home/nsksbjii/.config

- name: copy passwords
  copy:
    src: /home/nsksbjii/files/K_E_Y_S.kdbx
    dest: /home/nsksbjii/K_E_Y_S.kdbx
- name: copy zshrc
  copy:
    src: /home/nsksbjii/files/zshrc
    dest: /home/nsksbjii/.zshrc
