syntax on
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set smartcase
set nobackup
set undodir=$HOME/.vim/undodir
set undofile
set incsearch
call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'
Plug 'mbbill/undotree'
Plug 'https://github.com/ycm-core/YouCompleteMe.git'
Plug 'jremmen/vim-ripgrep'
Plug 'https://github.com/kien/ctrlp.vim.git'
call plug#end()

colorscheme gruvbox
set background=dark
let mapleader = " "
let g:netrw_browse_split=2
let g:netrw_winsize=25
let g:ycm_global_ycm_extra_conf = '$HOME/.vim/.ycm_extra_conf.py'
let g:ycm_global_ycm_extra_conf = '/home/ketrptr/.vim/plugged/YouCompleteMe/third_party/ycmd/.ycm_extr_conf.py'


nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <leader>u :UndotreeShow<CR>
nnoremap <leader>pv :wincmd pv<bar> :Ex <bar> :vertical resize 40<CR>

nnoremap <silent> <leader>gd :YcmCompleter GoTo<CR>
nnoremap <silent> <leader>gf :YcmCompleter FixIt<CR>
